name: rainforest_biz_project
description: ''
version: '1.1'
author: avaloorai@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforestbizproject
  parentArtefactID: avalooraigmailcomteam
  buildSystem: wheel
  author: null
  createdAt: '2025-07-20 17:01:24'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: avaloorai@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-07-20 17:01:24'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: avaloorai@gmail.com
    createdAt: '2025-07-20 17:49:03'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 30819
        datasetType: Database
        description: ''
        author: avaloorai@gmail.com
        createdAt: '2025-07-20 17:49:03'
templates: {}
jobs:
  jobs/daily_accounts:
    name: daily_accounts
    description: ''
    fabricUID: 30819
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: oncall@rainforest.biz
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/enrich_accounts
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2025-07-20 17:54:39'
    author: avaloorai@gmail.com
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-07-20 17:01:24'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-07-20T17:01:24.339695Z'
  name: plibMaven
  version: 8.10.3
  id: '1908738106'
  createdAt: '2025-07-20T17:01:24.339695Z'
  type: plibMaven
- modifiedAt: '2025-07-20T17:01:24.339695Z'
  name: plibPypi
  version: 1.9.49
  id: '1569193353'
  createdAt: '2025-07-20T17:01:24.339695Z'
  type: plibPypi
projectDependencies:
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2025-07-20 16:58:43'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.46
    isDefault: true
    author: null
    createdAt: '2025-07-20 16:58:43'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-07-20 16:58:43'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
